<a href="https://colab.research.google.com/github/Vapemo/Numpy/blob/main/Copia_de_Numpy_Jomwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Tarea de Numpy**

Este notebook es el de los ejercicios >:)

In [ ]:
!pip install numpy
import numpy as np

# Probando si si jala el numpy
my_arreglow = np.array([1, 2, 3, 4, 5])

print(my_arreglow)
print(np.mean(my_arreglow))


[1 2 3 4 5]
3.0


## Ejercicios de refuerzo

### **Ejercicio 1 - Crear un array de ceros:**
Crea un array de tamaño (3, 4) lleno de ceros.

In [ ]:
# Solución (:

array_ceros=np.zeros((3,4))
print(array_ceros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### **Ejercicio 2-  Suma de elementos:**
   Dado el array [1, 2, 3, 4, 5], calcula la suma de todos sus elementos usando NumPy.

In [ ]:
# Solucion :)
array_1=np.array([1, 2, 3, 4,5])
print(array_1)
suma_array=np.sum(array_1)
print(suma_array)

[1 2 3 4 5]
15


### **Ejercicio 3 - Encontrar el máximo y mínimo:**
Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.

In [ ]:
# Solución:)

array=np.array([10, 20, 30, 40, 50])
print(array)
array = np.array([10, 20, 30, 40, 50])
maximo=np.max(array)
print("el valor máximo es:",maximo)
minimo=np.min(array)
print("el valor mínimo es :",minimo)


[10 20 30 40 50]
el valor máximo es: 50
el valor mínimo es : 10


### **Ejercicio 4 - Encontrar el máximo y mínimo:**
 Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.


In [ ]:
# Solución:)

array=np.array([10, 20, 30, 40, 50])
print(array)
array = np.array([10, 20, 30, 40, 50])
maximo=np.max(array)
print("el valor máximo es:",maximo)
minimo=np.min(array)
print("el valor mínimo es :",minimo)



[10 20 30 40 50]
el valor máximo es: 50
el valor mínimo es : 10


### **Ejercicio 5 - Generar números aleatorios:**
  Genera un array de 5 números aleatorios entre 0 y 1.

In [ ]:
# Solución:)

array_aleatorio=np.random.rand(5)
print(array_aleatorio)


[0.92439349 0.14340324 0.97165811 0.61914276 0.96960661]


### **Ejercicio 6 - Promedio de un array:**
Dado el array [5, 10, 15, 20, 25], calcula su promedio usando NumPy.

In [ ]:
#Solucion:)
array=np.array( [5, 10, 15, 20, 25])
print(array)
print("el promedio del array es:",np.mean(array))

[ 5 10 15 20 25]
el promedio del array es: 15.0


### **Ejercicio 7 - Concatenar dos arrays**
Dados los arrays A = [1, 2, 3] y B = [4, 5, 6], concaténalos en un solo array.

In [ ]:
#Solucion:
A=np.array([1, 2, 3] )
B=np.array( [4, 5, 6])
print(A,B)
concatenados=np.concatenate((A,B))
print(concatenados)

[1 2 3] [4 5 6]
[1 2 3 4 5 6]


### **Ejercicio 8 - Reshape de un Array**
Dado el array [1, 2, 3, 4, 5, 6], cámbialo a una matriz de 2x3.

In [ ]:
#Solución:)
array=np.array([1, 2, 3, 4, 5, 6])
print(array)

arr_2x3 = array.reshape(2,3)
print("Reshape a 2x3:\n", arr_2x3)

[1 2 3 4 5 6]
Reshape a 2x3:
 [[1 2 3]
 [4 5 6]]


### **Ejercicio 9 - Producto punto (dot product):**
Dados dos arrays A = [1, 2, 3] y B = [4, 5, 6], calcula su producto punto

In [ ]:
#Solución:)
A=np.array([1, 2, 3])
B=np.array( [4, 5, 6])
print(A,B)
producto_punto=np.dot(A,B)
print("El produccto punto es:",producto_punto)

[1 2 3] [4 5 6]
El produccto punto es: 32


### **Ejercicio 10 - Reorganizar un array:**
Dado el array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], conviértelo en una matriz (2, 5).

In [ ]:
#Solución:)
array=np.array( [1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(array)
arr_2x5=array.reshape(2,5)
print("Reshape a 2x5:\n", arr_2x5)

[ 1  2  3  4  5  6  7  8  9 10]
Reshape a 2x5:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### **Ejercicio extra - Encontrar el *k*-ésimo elemento más pequeño en un array**
Dado arr = np.array([9, 3, 6, 2, 1, 7]), encuentra el 3er elemento más pequeño sin ordenar el array completo.

**Pista solución 1**: Se puede hacer con un método de Numpy

**Pista solución 2**: El código se hace más complicado, pero se puede resolver con ciclos iterativos.

In [ ]:
#Solucion :o

arr = np.array([9, 3, 6, 2, 1, 7])
tercer_menor = np.partition(arr, 2)[2]

print("El tercer elemento más pequeño es:", tercer_menor)


El tercer elemento más pequeño es: 3


## **Ejercicios aplicados**

### **Ejercicio: Cálculo de ROI (Retorno de Inversión)**
Dadas las inversiones ([1000, 1500, 2000]) y sus retornos ([1200, 1650, 1800]), calcula el ROI porcentual para cada caso.

*(Fórmula: ROI = (retorno - inversión) / inversión * 100)*

In [ ]:
# Solucion del ROIROIROIROIORIORI

inversion=np.array([1000, 1500, 2000])
retorno=np.array ([1200, 1650, 1800])
ROI = ((retorno - inversion) / inversion) * 100
print("El ROI es:", ROI)

El ROI es: [ 20.  10. -10.]


### **Ejercicio: Normalización de Datos**
Tienes un dataset de precios de productos (en USD): [250, 320, 150, 500, 210]. Normaliza los valores al rango [0, 1] para compararlos en una escala común.

**Formulita de la normalización**: (x - min) / (max - min): Para una escala valores entre 0 y 1.

In [ ]:
precios_producto=np.array( [250, 320, 150, 500, 210])
minimo = np.min(precios_producto)
maximo = np.max(precios_producto)

precios_normalizados = (precios_producto - minimo) / (maximo - minimo)

print("Precios normalizados:", precios_normalizados)

Precios normalizados: [0.28571429 0.48571429 0.         1.         0.17142857]


### **Ejercicio: Filtrado de Datos**
En un array de ventas diarias ([1200, 0, 750, 2400, 0, 1800]), reemplaza los ceros (días sin ventas) por el promedio de los días con ventas.

In [ ]:
ventas_diarias=np.array([1200, 0, 750, 2400, 0, 1800])
promedio_ventas=np.mean(ventas_diarias[ventas_diarias > 0])  #promedio de los que no son 0
ventas_diarias[ventas_diarias==0]=promedio_ventas #busca los que son cero y les ponen el valor del promedio
print("las ventas  actualizadas",ventas_diarias)

las ventas  actualizadas [1200 1537  750 2400 1537 1800]


### **Ejercicio - Análisis de Presión Arterial**
Tenemos un dataset de mediciones de presión arterial sistólica (mmHg) de 10 pacientes:
[120, 135, 140, 118, 150, 130, 160, 125, 142, 128].

Calculen:
- Media y desviación estándar.
- Identifiquen valores fuera del rango normal (90–140 mmHg).

In [ ]:
presion_arterial=np.array ([120, 135, 140, 118, 150, 130, 160, 125, 142, 128])
media=presion_arterial.mean()
print("la media es ",media)
desviacion_estandar=presion_arterial.std()
print("desviacion estandar es:",desviacion_estandar)

la media es  134.8
desviacion estandar es: 12.69488085804668


### **Ejercicio - Cálculo del PIB per Cápita**
Dados el PIB (en millones de USD) [500, 320, 700, 450] y la población (en millones) [10, 8, 12, 9] de 4 países, calculen el PIB per cápita y determinen el país con el mayor valor.

In [ ]:
PIB =np.array( [500, 320, 700, 450])
poblacion=np.array([10, 8, 12, 9] )
pib_per_capita = PIB / poblacion
indice_mayor = np.argmax(pib_per_capita)

print("PIB per cápita de cada país:", pib_per_capita)
print(f"El país con mayor PIB per cápita es el país {indice_mayor + 1} con un valor de {pib_per_capita[indice_mayor]:.2f} millones USD por persona.")#2f para los decimales

PIB per cápita de cada país: [50.         40.         58.33333333 50.        ]
El país con mayor PIB per cápita es el país 3 con un valor de 58.33 millones USD por persona.


### **Ejercicio - Sistema de Drops (Probabilidades)**
En un videojuego RPG, los enemigos al ser vencidos, pueden dropear (soltar):
- 0 = Nada (50%).
- 1 = Poción (30%).
- 2 = Arma (15%).
- 3 = Artefacto (5%).

Simula 100 drops y cuenta cuántos artefactos se obtuvieron.

*Ejemplo de salida*:

```
Artifactos obtenidos: 3
```



In [ ]:
valores = [0, 1, 2, 3]
probabilidades = [0.5, 0.3, 0.15, 0.05]

# simula 100 drops
drops = np.random.choice(valores, size=100, p=probabilidades)

# se cuenta cuántos artefactos  de valor 3  se obtuvieron
artefactos = np.count_nonzero(drops == 3)

print("Artefactos obtenidos:", artefactos)

Artefactos obtenidos: 7
